"""
Type stubs for the Nostr module.

This file provides type annotations for the Nostr module, enabling better
type checking and autocompletion in IDEs. It defines the expected types
for classes, functions, and variables used within the Nostr module.

Note: This is a type stub file and does not contain any executable code.
"""

import asyncio
from logging import Logger
from pathlib import Path
from typing import ClassVar, List, Optional

from nostr_sdk import (  # type: ignore
    Client,
    Event,
    EventBuilder,
    EventId,
    Events,
    Filter,
    HandleNotification,
    Keys,
    NostrSigner,
    PublicKey,
    RelayMessage,
    UnsignedEvent,
)

from .models import NostrKeys, Product, Profile, Stall

class NostrClient:
    """
    NostrClient implements the set of Nostr utilities required for higher level functions
    implementations like the Marketplace.
    """

    logger: ClassVar[Logger]
    relay: str
    keys: Keys
    nostr_signer: NostrSigner
    client: Client
    connected: bool
    profile: Profile
    notification_task: Optional[asyncio.Task]
    received_eose: bool
    private_message: UnsignedEvent = None
    direct_message: Event = None

    def __init__(self, relay: str, private_key: str) -> None: ...
    def delete_event(self, event_id: str, reason: Optional[str] = None) -> str: ...
    # def publish_event(self, event_builder: EventBuilder) -> EventId: ...
    def get_profile(self) -> Profile: ...
    def listen_for_messages(self) -> str: ...
    def publish_event(self, kind: int, content: str) -> str: ...
    def publish_note(self, text: str) -> str: ...
    def publish_product(self, product: Product) -> str: ...
    def publish_profile(self) -> str: ...
    def publish_stall(self, stall: Stall) -> str: ...
    def retrieve_marketplace_merchants(
        self, owner: str, marketplace_name: str
    ) -> set[Profile]: ...
    def retrieve_products_from_merchant(self, merchant: str) -> List[Product]: ...
    def retrieve_profile(self, public_key: str) -> Profile: ...
    def retrieve_stalls_from_merchant(self, merchant: str) -> List[Stall]: ...
    def retrieve_all_merchants(self) -> set[Profile]: ...
    def send_private_message(self, public_key: str, message: str) -> str: ...
    def stop_notifications(self) -> None: ...
    @classmethod
    def set_logging_level(cls, logging_level: int) -> None: ...
    async def _async_connect(self) -> None: ...
    async def _async_listen_for_messages(self) -> str: ...
    async def _async_publish_event(self, event_builder: EventBuilder) -> EventId: ...
    async def _async_publish_note(self, text: str) -> EventId: ...
    async def _async_publish_product(self, product: Product) -> EventId: ...
    async def _async_publish_profile(self) -> EventId: ...
    async def _async_publish_stall(self, stall: Stall) -> EventId: ...
    async def _async_retrieve_all_stalls(self) -> Events: ...
    async def _async_retrieve_events(self, events_filter: Filter) -> Events: ...
    async def _async_retrieve_products_from_merchant(
        self, merchant: PublicKey
    ) -> Events: ...
    async def _async_retrieve_profile(self, author: PublicKey) -> Profile: ...
    async def _async_retrieve_stalls_from_seller(self, seller: PublicKey) -> Events: ...
    async def _async_send_private_message(
        self, public_key: PublicKey, message: str
    ) -> EventId: ...
    async def _start_notifications(self) -> None: ...

    class MyNotificationHandler(HandleNotification):
        def __init__(self, nostr_client: NostrClient): ...
        async def handle_msg(self, relay_url: str, msg: RelayMessage) -> None: ...
        async def handle(
            self, relay_url: str, subscription_id: str, event: Event
        ) -> None: ...

def generate_keys(env_var: str, env_path: Optional[Path] = None) -> NostrKeys: ...
