from logging import Logger
from typing import ClassVar

from phi.tools import Toolkit

from agentstr.models import AgentProfile, NostrProfile
from agentstr.nostr import NostrClient

class Buyer(Toolkit):
    logger: ClassVar[Logger]
    sellers: set[NostrProfile]
    relay: str
    _nostr_client: NostrClient

    def __init__(self, buyer_profile: AgentProfile, relay: str) -> None: ...
    def find_seller_by_name(self, name: str) -> str: ...
    def find_seller_by_public_key(self, public_key: str) -> str: ...
    def find_sellers_by_location(self, location: str) -> str: ...
    def get_profile(self) -> str: ...
    def get_relay(self) -> str: ...
    def get_seller_collections(self, public_key: str) -> str: ...
    def get_seller_count(self) -> str: ...
    def get_seller_products(self, public_key: str) -> str: ...
    def get_sellers(self) -> str: ...
    def refresh_sellers(self) -> str: ...
    def _refresh_sellers(self) -> None: ...
