from enum import Enum
from logging import Logger
from typing import ClassVar, List, Optional, Union

from nostr_sdk import (
    Keys,
    Metadata,
    ProductData,
    PublicKey,
    ShippingCost,
    ShippingMethod,
    StallData,
)
from pydantic import BaseModel

class Profile:
    logger: ClassVar[Logger]
    about: str
    display_name: str
    name: str
    picture: str
    website: str

    def __init__(self) -> None: ...
    def get_about(self) -> str: ...
    def get_display_name(self) -> str: ...
    def get_name(self) -> str: ...
    def get_picture(self) -> str: ...
    def get_website(self) -> str: ...
    def set_about(self, about: str) -> None: ...
    def set_display_name(self, display_name: str) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_picture(self, picture: str) -> None: ...
    def set_website(self, website: str) -> None: ...
    def to_json(self) -> str: ...

class AgentProfile(Profile):
    WEB_URL: ClassVar[str]
    profile_url: str
    keys: Keys

    def __init__(self, keys: Keys) -> None: ...
    @classmethod
    def from_metadata(cls, metadata: Metadata, keys: Keys) -> "AgentProfile": ...
    def get_private_key(self) -> str: ...
    def get_public_key(self) -> str: ...
    def to_json(self) -> str: ...

class NostrProfile(Profile):
    public_key: PublicKey
    profile_url: str
    WEB_URL: ClassVar[str]

    def __init__(self, public_key: PublicKey) -> None: ...
    @classmethod
    def from_metadata(
        cls, metadata: Metadata, public_key: PublicKey
    ) -> "NostrProfile": ...
    def get_public_key(self) -> str: ...
    def get_profile_url(self) -> str: ...
    def get_zip_codes(self) -> List[str]: ...
    def to_json(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class MerchantProduct:
    product: ProductData
    def __init__(
        self,
        id: str,
        stall_id: str,
        name: str,
        description: str,
        images: List[str],
        currency: str,
        price: int,
        quantity: int,
        shipping: List[ShippingCost],
        categories: Optional[List[str]] = None,
        specs: Optional[List[List[str]]] = None,
    ) -> None: ...
    def get_data(self) -> ProductData: ...
    def name(self) -> str: ...

class MerchantStall:
    stall: StallData
    def __init__(
        self,
        id: str,
        name: str,
        description: str,
        currency: str,
        shipping: List[ShippingMethod],
    ) -> None: ...
    def get_data(self) -> StallData: ...
    def name(self) -> str: ...
