from enum import Enum
from logging import Logger
from typing import ClassVar, Optional, Union

class Profile:
    logger: ClassVar[Logger]
    about: str
    display_name: str
    name: str
    picture: str
    website: str

    def __init__(self) -> None: ...
    def get_about(self) -> str: ...
    def get_display_name(self) -> str: ...
    def get_name(self) -> str: ...
    def get_picture(self) -> str: ...
    def get_website(self) -> str: ...
    def set_about(self, about: str) -> None: ...
    def set_display_name(self, display_name: str) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_picture(self, picture: str) -> None: ...
    def set_website(self, website: str) -> None: ...
    def to_json(self) -> str: ...
